/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { UserPreferences } from "./UserPreferences";
import { UserPreferencesCountArgs } from "./UserPreferencesCountArgs";
import { UserPreferencesFindManyArgs } from "./UserPreferencesFindManyArgs";
import { UserPreferencesFindUniqueArgs } from "./UserPreferencesFindUniqueArgs";
import { DeleteUserPreferencesArgs } from "./DeleteUserPreferencesArgs";
import { UserPreferencesService } from "../userPreferences.service";
@graphql.Resolver(() => UserPreferences)
export class UserPreferencesResolverBase {
  constructor(protected readonly service: UserPreferencesService) {}

  async _userPreferencesItemsMeta(
    @graphql.Args() args: UserPreferencesCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [UserPreferences])
  async userPreferencesItems(
    @graphql.Args() args: UserPreferencesFindManyArgs
  ): Promise<UserPreferences[]> {
    return this.service.userPreferencesItems(args);
  }

  @graphql.Query(() => UserPreferences, { nullable: true })
  async userPreferences(
    @graphql.Args() args: UserPreferencesFindUniqueArgs
  ): Promise<UserPreferences | null> {
    const result = await this.service.userPreferences(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => UserPreferences)
  async deleteUserPreferences(
    @graphql.Args() args: DeleteUserPreferencesArgs
  ): Promise<UserPreferences | null> {
    try {
      return await this.service.deleteUserPreferences(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
